
export const GET_LOTS_REQUEST=' GET_LOTS_REQUEST'
export const GET_LOTS_SUCCESS=' GET_LOTS_SUCCESS'
export const GET_LOTS_FAIL=' GET_LOTS_FAIL'
export const GET_CATEGORIES_REQUEST=' GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS=' GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL=' GET_CATEGORIES_FAIL'
export const ADD_CUSTOMER_LOT='ADD_CUSTOMER_LOT'
export const REMOVE_CUSTOMER_LOT="REMOVE_CUSTOMER_LOT"
export const INCREMENT_COUNT_CUSTOMER_LOT="INCREMENT_COUNT_CUSTOMER_LOT"
export const DECREMENT_COUNT_CUSTOMER_LOT="DECREMENT_COUNT_CUSTOMER_LOT"