import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useDispatch,useSelector } from 'react-redux'
import { useEffect } from 'react'
import { GetLotsFail,GetLotsRequest,GetLotsSuccess } from '../redux/shopping/shoppingActions'
import { RootState,AppDispatch } from '../redux/store'
import ReactLoading from 'react-loading';
import Loading from "./Loading"
import axios from 'axios'
import Lots from './lots'
import Categories from './categories'
import { useRouter } from 'next/router'
const Home: NextPage = () => {
   const router=useRouter()
  const dispatch:AppDispatch=useDispatch()
  const state=useSelector((state:RootState)=>state)
  
  const getLots=()=>{
  //  return async function (dispatch:AppDispatch){
  //     dispatch(GetLotsRequest())
  //     try{
       
  //       const response=await axios.get("https://fakestoreapi.com/products")
  //       console.log(response.data)
  //       dispatch(GetLotsSuccess(response.data))
  //     }
  //     catch(er:any){
  //       console.log(er)
  //       dispatch(GetLotsFail(er.messege))
  //     }
  //   } 
    return async(dispatch:AppDispatch)=>{
    
      dispatch(GetLotsRequest())
      try{
       
        const response=await axios.get("https://fakestoreapi.com/products")
        console.log(response.data)
        dispatch(GetLotsSuccess(response.data))
      }
      catch(er:any){
        console.log(er.messege)
        dispatch(GetLotsFail(er.message))
      }
    
    }
  }
useEffect(()=>{

  dispatch(getLots());
  
  // return ()=>{
  //   // console.log("t")
  // }
},[])

  return (
    
    <>

   

    {console.log(state)}
    {/* {console.log(lots)} */}
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
 <h1 className={styles.title}>
         salam  dadach!
        </h1>
      <main className={styles.main}>
      {state.isLoading==false ? (<Categories lots={state.lots}/>):( <Loading/>)}
      {/* {console.log(lots)} */}
      {/* {state.isLoading==false ? (<Lots lots={state.lots}/>):( <Loading/>)} */}
      
         {/* use Router just likes navigate() in react-router */}
              {/* <button className="btn btn-primary" onClick={()=>{console.log("a"); router.push("/about") }}>test</button>
               */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
    </>
  )
}

export default Home
